[versions]

android-gradle-plugin = "8.11.1"
kotlin = "2.2.0"
hilt = "2.57.1"
ksp = "2.2.0-2.0.2"
compose = "2.2.0"
appcompat = "1.7.1"
recyclerview = "1.4.0"
constraintlayout = "2.2.1"
material = "1.12.0"
room = "2.7.2"
compose-runtime-livedata = "1.9.0"
stetho = "1.5.1"
lifecycle = "2.9.2"
okhttp = "5.1.0"
retrofit = "3.0.0"
moshi = "1.15.2"
coil = "3.3.0"
timber = "4.7.1"
coroutines = "1.10.2"
compose-bom = "2025.08.00"
constraintlayout-compose = "1.1.1"
activity-compose = "1.11.0"
hilt-navigation-compose = "1.3.0"
mockito = "5.19.0"
junit = "4.13.2"
turbine = "1.0.0"
androidx-test-core = "1.6.1"
androidx-test-ext-junit = "1.3.0"
androidx-test-runner = "1.6.1"
androidx-test-rules = "1.6.1"
espresso-core = "3.6.1"
arch-core-testing = "2.2.0"
compose-ui-test = "1.9.1"

[libraries]

appcompat = { module = "androidx.appcompat:appcompat", version.ref = "appcompat" }
recyclerview = { module = "androidx.recyclerview:recyclerview", version.ref = "recyclerview" }
constraintlayout = { module = "androidx.constraintlayout:constraintlayout", version.ref = "constraintlayout" }
material = { module = "com.google.android.material:material", version.ref = "material" }

room-ktx = { module = "androidx.room:room-ktx", version.ref = "room" }
room-compiler = { module = "androidx.room:room-compiler", version.ref = "room" }

compose-runtime-livedata = { module = "androidx.compose.runtime:runtime-livedata", version.ref = "compose-runtime-livedata" }

stetho = { module = "com.facebook.stetho:stetho", version.ref = "stetho" }

lifecycle-extensions = { module = "androidx.lifecycle:lifecycle-extensions", version = "2.2.0" }

okhttp-logging-interceptor = { module = "com.squareup.okhttp3:logging-interceptor", version.ref = "okhttp" }
okhttp = { module = "com.squareup.okhttp3:okhttp", version.ref = "okhttp" }

retrofit = { module = "com.squareup.retrofit2:retrofit", version.ref = "retrofit" }
retrofit-converter-moshi = { module = "com.squareup.retrofit2:converter-moshi", version.ref = "retrofit" }

moshi-kotlin = { module = "com.squareup.moshi:moshi-kotlin", version.ref = "moshi" }
moshi-kotlin-codegen = { module = "com.squareup.moshi:moshi-kotlin-codegen", version.ref = "moshi" }

coil-compose = { module = "io.coil-kt.coil3:coil-compose", version.ref = "coil" }
coil-network-okhttp = { module = "io.coil-kt.coil3:coil-network-okhttp", version.ref = "coil" }

timber = { module = "com.jakewharton.timber:timber", version.ref = "timber" }

kotlinx-coroutines-android = { module = "org.jetbrains.kotlinx:kotlinx-coroutines-android", version.ref = "coroutines" }
kotlinx-coroutines-core = { module = "org.jetbrains.kotlinx:kotlinx-coroutines-core", version.ref = "coroutines" }

lifecycle-viewmodel-ktx = { module = "androidx.lifecycle:lifecycle-viewmodel-ktx", version.ref = "lifecycle" }
lifecycle-runtime-ktx = { module = "androidx.lifecycle:lifecycle-runtime-ktx", version.ref = "lifecycle" }
lifecycle-livedata-ktx = { module = "androidx.lifecycle:lifecycle-livedata-ktx", version.ref = "lifecycle" }

compose-bom = { module = "androidx.compose:compose-bom", version.ref = "compose-bom" }
compose-ui = { module = "androidx.compose.ui:ui" }
compose-material3 = { module = "androidx.compose.material3:material3" }
compose-ui-tooling = { module = "androidx.compose.ui:ui-tooling" }
compose-ui-tooling-preview = { module = "androidx.compose.ui:ui-tooling-preview" }
compose-ui-graphics = { module = "androidx.compose.ui:ui-graphics" }

constraintlayout-compose = { module = "androidx.constraintlayout:constraintlayout-compose", version.ref = "constraintlayout-compose" }
activity-compose = { module = "androidx.activity:activity-compose", version.ref = "activity-compose" }

dagger = { module = "com.google.dagger:dagger", version.ref = "hilt" }
dagger-compiler = { module = "com.google.dagger:dagger-compiler", version.ref = "hilt" }
hilt-android = { module = "com.google.dagger:hilt-android", version.ref = "hilt" }
hilt-compiler = { module = "com.google.dagger:hilt-compiler", version.ref = "hilt" }
hilt-navigation-compose = { module = "androidx.hilt:hilt-navigation-compose", version.ref = "hilt-navigation-compose" }
hilt-android-testing = { module = "com.google.dagger:hilt-android-testing", version.ref = "hilt" }

mockito-core = { module = "org.mockito:mockito-core", version.ref = "mockito" }
kotlinx-coroutines-test = { module = "org.jetbrains.kotlinx:kotlinx-coroutines-test", version.ref = "coroutines" }
junit = { module = "junit:junit", version.ref = "junit" }
turbine = { module = "app.cash.turbine:turbine", version.ref = "turbine" }

mockito-android = { module = "org.mockito:mockito-android", version = "5.18.0" }
mockwebserver = { module = "com.squareup.okhttp3:mockwebserver", version = "5.1.0" }

androidx-test-core = { module = "androidx.test:core", version.ref = "androidx-test-core" }
androidx-test-ext-junit = { module = "androidx.test.ext:junit", version.ref = "androidx-test-ext-junit" }
androidx-test-runner = { module = "androidx.test:runner", version.ref = "androidx-test-runner" }
androidx-test-rules = { module = "androidx.test:rules", version.ref = "androidx-test-rules" }
espresso-core = { module = "androidx.test.espresso:espresso-core", version.ref = "espresso-core" }
arch-core-testing = { module = "androidx.arch.core:core-testing", version.ref = "arch-core-testing" }
room-testing = { module = "androidx.room:room-testing", version.ref = "room" }

compose-ui-test-junit4 = { module = "androidx.compose.ui:ui-test-junit4", version.ref = "compose-ui-test" }
compose-ui-test-manifest = { module = "androidx.compose.ui:ui-test-manifest", version.ref = "compose-ui-test" }


[plugins]

android-application = { id = "com.android.application", version.ref = "android-gradle-plugin" }
kotlin-android = { id = "org.jetbrains.kotlin.android", version.ref = "kotlin" }
hilt = { id = "com.google.dagger.hilt.android", version.ref = "hilt" }
ksp = { id = "com.google.devtools.ksp", version.ref = "ksp" }
compose = { id = "org.jetbrains.kotlin.plugin.compose", version.ref = "compose" }

